language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

os:
  - linux

before_script:
  - if [ "`phpenv version-name`" != "hhvm" ]; then echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" != "hhvm" ]; then echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" == "hhvm" ]; then echo 'opcache.enable=1' >> /etc/hhvm/php.ini; fi
  - if [ "`phpenv version-name`" == "hhvm" ]; then echo 'opcache.enable_cli=1' >> /etc/hhvm/php.ini; fi
  - composer self-update
  - composer install --dev --prefer-source
  - mkdir tests/PHPUnit/WURFL/Configuration/cache/
  - chmod -R 777 tests/PHPUnit/WURFL/Configuration/cache/

script:
# xdebug is not installed on HHVM and PHP 7, so we are skipping the creation of code coverage data there
  - if [ "`phpenv version-name`" == "5.3" ] || [ "`phpenv version-name`" == "5.4" ] || [ "`phpenv version-name`" == "5.5" ] || [ "`phpenv version-name`" == "5.6" ]; then vendor/bin/phpunit --no-configuration --coverage-text --coverage-clover=coverage.clover --colors --verbose --bootstrap tests/PHPUnit/bootstrap.php tests/PHPUnit/WURFLTestsSuite.php; fi
  - if [ "`phpenv version-name`" != "5.3" ] && [ "`phpenv version-name`" != "5.4" ] && [ "`phpenv version-name`" != "5.5" ] && [ "`phpenv version-name`" != "5.6" ]; then vendor/bin/phpunit --no-configuration --colors --verbose --bootstrap tests/PHPUnit/bootstrap.php tests/PHPUnit/WURFLTestsSuite.php; fi
  - vendor/bin/phpcs --standard=psr2 -np docs examples tests tools WURFL
  - vendor/bin/php-cs-fixer fix --dry-run -vv

after_script:
  - rm -R -f tests/PHPUnit/WURFL/Configuration/cache/
  - rmdir tests/PHPUnit/WURFL/Configuration/cache/
  # xdebug is not installed on HHVM and PHP 7, so we have no code coverage data to send
  - if [ "`phpenv version-name`" == "5.3" ] || [ "`phpenv version-name`" == "5.4" ] || [ "`phpenv version-name`" == "5.5" ] || [ "`phpenv version-name`" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "`phpenv version-name`" == "5.3" ] || [ "`phpenv version-name`" == "5.4" ] || [ "`phpenv version-name`" == "5.5" ] || [ "`phpenv version-name`" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi